//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostOfGasRefill
    {
        public int CostOfGasRefillID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string RefillPlaceName { get; set; }
        public Nullable<int> AmountRefilledInLiters { get; set; }
        public Nullable<int> CostOfRefill { get; set; }
        public Nullable<int> IDTravelWarrant { get; set; }
    
        public virtual TravelWarrant TravelWarrant { get; set; }
    }
}
