//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesHelperUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombDefinition
    {
        public int Id { get; set; }
        public Nullable<int> FatPerCent { get; set; }
        public Nullable<int> CarbPerCent { get; set; }
        public Nullable<int> ProteinPerCent { get; set; }
        public Nullable<int> TotalPer { get; set; }
        public int MealNameID { get; set; }
        public Nullable<int> MealCombinationID { get; set; }
    
        public virtual MealCombination MealCombination { get; set; }
        public virtual MealName MealName { get; set; }
    }
}
