//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesHelperUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealCombination
    {
        public MealCombination()
        {
            this.CombDefinitions = new HashSet<CombDefinition>();
        }
    
        public int Id { get; set; }
        public Nullable<int> NumOfMeals { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
    
        public virtual ICollection<CombDefinition> CombDefinitions { get; set; }
    }
}
