//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesHelperUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int Id { get; set; }
        public Nullable<int> IDMenu { get; set; }
        public Nullable<int> IDMealName { get; set; }
        public Nullable<int> IDGood { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual MealName MealName { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
