//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesHelperUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasuringUnit
    {
        public MeasuringUnit()
        {
            this.Goods = new HashSet<Good>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Good> Goods { get; set; }
    }
}
