//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesHelperUser
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealName
    {
        public MealName()
        {
            this.CombDefinitions = new HashSet<CombDefinition>();
            this.Meals = new HashSet<Meal>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CombDefinition> CombDefinitions { get; set; }
        public virtual ICollection<Meal> Meals { get; set; }
    }
}
