//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupyingDriver
    {
        public int OccupyingDriverID { get; set; }
        public Nullable<System.DateTime> DateOccupyingStarted { get; set; }
        public Nullable<int> IDDriver { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
