//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ServiceID { get; set; }
        public string PlaceOfService { get; set; }
        public string NameOfService { get; set; }
        public Nullable<int> CostOfService { get; set; }
        public string ServiceInfo { get; set; }
        public Nullable<int> IDVehicle { get; set; }
        public Nullable<int> IDTravelWarrant { get; set; }
    
        public virtual TravelWarrant TravelWarrant { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
