//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesHelperUser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public Good()
        {
            this.Meals = new HashSet<Meal>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Energy_kcal { get; set; }
        public Nullable<int> Energy_kJ { get; set; }
        public Nullable<int> IDType { get; set; }
        public Nullable<int> IDMeasuringUnit { get; set; }
    
        public virtual FoodType FoodType { get; set; }
        public virtual MeasuringUnit MeasuringUnit { get; set; }
        public virtual ICollection<Meal> Meals { get; set; }
    }
}
